language: python
python:
 - "3.6.1"

#dependacies and libraries to install
install: pip install -r requirements.txt

env: 
 - SECRET_KEY='super awesome secret #$%^*('
 - APP_SETTINGS='development'

before_script:
  - psql -c "CREATE DATABASE test_db_brighter_events;" -U postgres

script:
- nosetests --with-coverage --cover-package=app

after_success:
 - coveralls --config_file .coveragerc
  