language: python
python:
 - "3.6.1"

#dependacies and libraries to install
install: pip install -r requirements.txt

script:
- nosetests --with-coverage --cover-package=tests

after_success:
 - coveralls --config_file .coveragerc
  