language: python
python:
 - "3.6.1"
 
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
#dependacies and libraries to install
install: pip install -r requirements.txt

before_script:
  - sudo psql -c "CREATE DATABASE test_db_brighter_events;" -U postgres

script:
- nosetests --with-coverage --cover-package=app

after_success:
 - coveralls --config_file .coveragerc


  