language: python
python:
 - "3.6.1"

#dependacies and libraries to install
install: pip install -r requirements.txt

script: sh run_travis.sh --cov-config .coveragerc

after_success:
 - coveralls --config_file .coveragerc
  