language: python
 - "3.6"

script:
 - python test_app_tests.py > /dev/null & nosetests --with-coverage

#dependacies and libraries to install
install: 
 - pip install -t lib -r requirements.txt

after_success:
 - coveralls
  