language: python
 - "3.6.1"

#dependacies and libraries to install
install: 
 - pip install -r requirements.txt
 - pip install nose --upgrade

script:
 - nosetests tests/

after_success:
 - coveralls
  