language: python
python:
 - "3.6.1"

#dependacies and libraries to install
install: pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE test_db_brighter_events;" -U postgres

env:
  export SQLALCHEMY_DATABASE_URI=postgresql://localhost/brighter_events
  SECRET_KEY=super awesome secret #$%^*(
  APP_SETTINGS=development

script:
- nosetests --with-coverage --cover-package=app

after_success:
 - coveralls --config_file .coveragerc
  