"""empty message

Revision ID: 3e24a6a3c0f8
Revises: 54eb1f8d6443
Create Date: 2018-02-24 00:50:23.613099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e24a6a3c0f8'
down_revision = '54eb1f8d6443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'rsvps', 'events', ['eventid'], ['eventid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rsvps', type_='foreignkey')
    # ### end Alembic commands ###
