"""make not attendind default value in rsvp

Revision ID: 54a96dcfc677
Revises: 268e68aec39e
Create Date: 2018-06-04 15:47:05.337933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a96dcfc677'
down_revision = '268e68aec39e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rsvps', sa.Column('date_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rsvps', 'date_updated')
    # ### end Alembic commands ###
