"""empty message

Revision ID: 54eb1f8d6443
Revises: 6485dc34e636
Create Date: 2018-02-24 00:21:03.089240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54eb1f8d6443'
down_revision = '6485dc34e636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_confirmed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_confirmed_on')
    op.drop_column('users', 'email_confirmed')
    # ### end Alembic commands ###
