"""empty message

Revision ID: 90142f8c769a
Revises: 
Create Date: 2018-01-09 23:53:46.014044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90142f8c769a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('user_public_id', sa.String(length=50), nullable=True))
    op.drop_column('events', 'userid')
    op.drop_column('events', 'cost')
    op.add_column('rsvps', sa.Column('user_public_id', sa.Integer(), nullable=True))
    op.drop_column('rsvps', 'userid')
    op.add_column('users', sa.Column('public_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'users', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'public_id')
    op.add_column('rsvps', sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('rsvps', 'user_public_id')
    op.add_column('events', sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('events', 'user_public_id')
    # ### end Alembic commands ###
