"""empty message

Revision ID: 95bc74fd8a2f
Revises: 90142f8c769a
Create Date: 2018-01-10 01:23:35.603928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95bc74fd8a2f'
down_revision = '90142f8c769a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'cost')
    # ### end Alembic commands ###
