"""make not attendind default value in rsvp

Revision ID: ccf49640ca6f
Revises: 54a96dcfc677
Create Date: 2018-06-04 15:47:36.732642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccf49640ca6f'
down_revision = '54a96dcfc677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rsvps', 'date_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rsvps', sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
