"""empty message

Revision ID: db5c0bb177ca
Revises: d6f4e171ca8b
Create Date: 2018-07-14 16:46:22.820042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5c0bb177ca'
down_revision = 'd6f4e171ca8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
