"""empty message

Revision ID: e226b1fac843
Revises: 95bc74fd8a2f
Create Date: 2018-01-10 21:25:52.075081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e226b1fac843'
down_revision = '95bc74fd8a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rsvps', sa.Column('user_pub_id', sa.String(length=50), nullable=True))
    op.drop_column('rsvps', 'user_public_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rsvps', sa.Column('user_public_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('rsvps', 'user_pub_id')
    # ### end Alembic commands ###
